services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: secunda
      POSTGRES_USER: secunda
      POSTGRES_PASSWORD: secunda
    networks:
      - secunda
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U secunda" ]
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - secunda
    volumes:
      - .:/opt/secunda
    depends_on:
      postgres:
        condition: service_healthy



networks:
  secunda:
    driver: bridge