"""initial

Revision ID: 8ab5d2dc378b
Revises: 
Create Date: 2025-07-04 00:43:22.483392

"""
import sqlalchemy as sa
from alembic import context, op
from sqlalchemy.sql import text
from sqlalchemy_utils import LtreeType

# revision identifiers, used by Alembic.
revision = '8ab5d2dc378b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS ltree')

    op.create_table('activity',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('path', LtreeType(), nullable=False),
    sa.CheckConstraint('nlevel(path) <= 3', name=op.f('ck_activity_check_ltree_depth')), # ограничить уровень вложенности деятельностей 3 уровням
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('office',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_office_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_office'))
    )
    op.create_table('organization_activity_association',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_organization_activity_association_activity_id_activity')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organization_activity_association_organization_id_organization')),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id', name=op.f('pk_organization_activity_association'))
    )
    op.create_table('phone',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_phone_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone'))
    )
    # ### end Alembic commands ###


def schema_downgrades():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    op.drop_table('organization_activity_association')
    op.drop_table('office')
    op.drop_table('organization')
    op.drop_table('activity')

    op.execute('DROP EXTENSION ltree;')
    # ### end Alembic commands ###


def data_upgrades():
    op.execute(text("""
        INSERT INTO activity (id, name, path) VALUES
            ('11111111-1111-1111-1111-111111111111', 'medicine', 'medicine'),
            ('22222222-2222-2222-2222-222222222222', 'education', 'education'),
            ('33333333-3333-3333-3333-333333333333', 'it', 'it'),
            ('44444444-4444-4444-4444-444444444444', 'construction', 'construction'),
            ('55555555-5555-5555-5555-555555555555', 'trade', 'trade'),
            ('66666666-6666-6666-6666-666666666666', 'dentistry', 'medicine.dentistry'),
            ('77777777-7777-7777-7777-777777777777', 'orthodontics', 'medicine.dentistry.orthodontics');
        """)
               )

    # Вставляем организации (organization)
    op.execute(text("""
        INSERT INTO organization (id, name) VALUES
        ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'городская больница №1'),
        ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'университет'),
        ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'it компания'),
        ('dddddddd-dddd-dddd-dddd-dddddddddddd', 'строительная фирма'),
        ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'торговый центр'),
        ('ffffffff-ffff-ffff-ffff-ffffffffffff', 'стоматологическая клиника "улыбка"');
    """)
               )

    # Вставляем связь организаций с видами деятельности
    op.execute(text("""
        INSERT INTO organization_activity_association (organization_id, activity_id) VALUES
        ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '11111111-1111-1111-1111-111111111111'),
        ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '22222222-2222-2222-2222-222222222222'),
        ('cccccccc-cccc-cccc-cccc-cccccccccccc', '33333333-3333-3333-3333-333333333333'),
        ('dddddddd-dddd-dddd-dddd-dddddddddddd', '44444444-4444-4444-4444-444444444444'),
        ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', '55555555-5555-5555-5555-555555555555'),
        ('ffffffff-ffff-ffff-ffff-ffffffffffff', '66666666-6666-6666-6666-666666666666'),
        ('ffffffff-ffff-ffff-ffff-ffffffffffff', '77777777-7777-7777-7777-777777777777');
    """)
               )

    # Вставляем офисы (office)
    op.execute(text("""
        INSERT INTO office (id, address, latitude, longitude, organization_id) VALUES
        ('a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1', 'ул.медицинская,1', 55.751244, 37.618423, 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
        ('b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2', 'ул.университетская,15', 55.752345, 37.619534, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
        ('c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3', 'ул.программистов,42', 55.753456, 37.620645, 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
        ('d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4', 'ул.строителей,7', 55.754567, 37.621756, 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
        ('e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5', 'ул.торговая,100', 55.755678, 37.622867, 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
        ('f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1', 'ул.зубная,32', 55.758789, 37.625678, 'ffffffff-ffff-ffff-ffff-ffffffffffff');
    """)
               )

    # Вставляем телефоны (phone)
    op.execute(text("""
        INSERT INTO phone (id, number, organization_id) VALUES
        ('1a1a1a1a-1a1a-1a1a-1a1a-1a1a1a1a1a1a', '74951111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
        ('2b2b2b2b-2b2b-2b2b-2b2b-2b2b2b2b2b2b', '74952222222', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),
        ('3c3c3c3c-3c3c-3c3c-3c3c-3c3c3c3c3c3c', '74953333333', 'cccccccc-cccc-cccc-cccc-cccccccccccc'),
        ('4d4d4d4d-4d4d-4d4d-4d4d-4d4d4d4d4d4d', '74954444444', 'dddddddd-dddd-dddd-dddd-dddddddddddd'),
        ('5e5e5e5e-5e5e-5e5e-5e5e-5e5e5e5e5e5e', '74955555555', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'),
        ('6f6f6f6f-6f6f-6f6f-6f6f-6f6f6f6f6f6f', '74956666666', 'ffffffff-ffff-ffff-ffff-ffffffffffff');
    """)
    )


def data_downgrades():
    ...

